Repository C1Z4/ourHour, pull requests merged in 2025-08, with the labels that each got.

#181 Release docker
  .gitignore
  backend/Dockerfile
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-release.yml
  backend/src/main/resources/application.yml
  docker-compose.dev.yml
  docker-compose.release.yml
  docker-compose.yml
Labels: config

#193 feat(fe): github-user 연동 관련 api 연동 및 ui 구현
  frontend/src/api/member/memberApi.ts
  frontend/src/api/user/userApi.ts
  frontend/src/components/common/info-menu/ProfileSheet.tsx
  frontend/src/hooks/queries/user/useUserMutations.ts
  frontend/src/routes/__root.tsx
  frontend/src/routes/oauth/github/callback.tsx
Labels: feat

#192 feat(be): 깃허브-유저 연동 기능 구현
  backend/src/main/java/com/ourhour/domain/member/dto/MyMemberInfoResDTO.java
  backend/src/main/java/com/ourhour/domain/project/exception/GithubException.java
  backend/src/main/java/com/ourhour/domain/user/controller/UserController.java
  backend/src/main/java/com/ourhour/domain/user/dto/GitHubCodeReqDTO.java
  backend/src/main/java/com/ourhour/domain/user/dto/GitHubConnectReqDTO.java
  backend/src/main/java/com/ourhour/domain/user/dto/GitHubUserInfoDTO.java
  backend/src/main/java/com/ourhour/domain/user/entity/GitHubTokenEntity.java
  backend/src/main/java/com/ourhour/domain/user/entity/UserEntity.java
  backend/src/main/java/com/ourhour/domain/user/entity/UserGitHubMappingEntity.java
  backend/src/main/java/com/ourhour/domain/user/repository/GitHubTokenRepository.java
  backend/src/main/java/com/ourhour/domain/user/repository/UserGitHubMappingRepository.java
  backend/src/main/java/com/ourhour/domain/user/service/UserService.java
  backend/src/main/java/com/ourhour/global/exception/ErrorCode.java
  backend/src/main/java/com/ourhour/global/util/.gitkeep
  backend/src/main/java/com/ourhour/global/util/EncryptionUtil.java
  backend/src/main/resources/db/migration/V10__update_github_sync_and_member_mapping.sql
  backend/src/test/resources/application.yml
Labels: feat

#194 feat(be): 깃허브 동기화 기능 구현
  backend/build.gradle
  backend/src/main/java/com/ourhour/OurhourApplication.java
  backend/src/main/java/com/ourhour/domain/comment/entity/CommentEntity.java
  backend/src/main/java/com/ourhour/domain/comment/repository/CommentRepository.java
  backend/src/main/java/com/ourhour/domain/comment/service/CommentService.java
  backend/src/main/java/com/ourhour/domain/org/mapper/OrgParticipantMemberMapper.java
  backend/src/main/java/com/ourhour/domain/project/annotation/GitHubSync.java
  backend/src/main/java/com/ourhour/domain/project/aspect/GitHubSyncAspect.java
  backend/src/main/java/com/ourhour/domain/project/controller/GitHubController.java
  backend/src/main/java/com/ourhour/domain/project/dto/IssueDeleteResDTO.java
  backend/src/main/java/com/ourhour/domain/project/dto/SyncStatusDTO.java
  backend/src/main/java/com/ourhour/domain/project/entity/GitHubSyncableEntity.java
  backend/src/main/java/com/ourhour/domain/project/entity/IssueEntity.java
  backend/src/main/java/com/ourhour/domain/project/entity/MilestoneEntity.java
  backend/src/main/java/com/ourhour/domain/project/enums/SyncOperation.java
  backend/src/main/java/com/ourhour/domain/project/enums/SyncStatus.java
  backend/src/main/java/com/ourhour/domain/project/exception/GithubException.java
  backend/src/main/java/com/ourhour/domain/project/github/GitHubClientFactory.java
  backend/src/main/java/com/ourhour/domain/project/github/GitHubDtoMapper.java
  backend/src/main/java/com/ourhour/domain/project/github/GitHubUtil.java
  backend/src/main/java/com/ourhour/domain/project/repository/IssueRepository.java
  backend/src/main/java/com/ourhour/domain/project/repository/MilestoneRepository.java
  backend/src/main/java/com/ourhour/domain/project/repository/ProjectGithubIntegrationRepository.java
  backend/src/main/java/com/ourhour/domain/project/service/GitHubSyncDomainService.java
  backend/src/main/java/com/ourhour/domain/project/service/GithubIntegrationService.java
  backend/src/main/java/com/ourhour/domain/project/service/IssueService.java
  backend/src/main/java/com/ourhour/domain/project/service/MilestoneService.java
  backend/src/main/java/com/ourhour/domain/project/service/ProjectGitHubService.java
  backend/src/main/java/com/ourhour/domain/project/sync/GitHubSyncHandler.java
  backend/src/main/java/com/ourhour/domain/project/sync/GitHubSyncManager.java
  backend/src/main/java/com/ourhour/domain/project/sync/IssueCommentSyncHandler.java
  backend/src/main/java/com/ourhour/domain/project/sync/IssueSyncHandler.java
  backend/src/main/java/com/ourhour/domain/project/sync/MilestoneSyncHandler.java
  backend/src/main/java/com/ourhour/domain/user/dto/GitHubRepositoryResDTO.java
  backend/src/main/java/com/ourhour/domain/user/dto/GitHubSyncTokenDTO.java
  backend/src/main/java/com/ourhour/domain/user/dto/GitHubTokenReqDTO.java
  backend/src/main/java/com/ourhour/domain/user/entity/ProjectGithubIntegrationEntity.java
  backend/src/main/java/com/ourhour/domain/user/repository/UserGitHubMappingRepository.java
  backend/src/main/java/com/ourhour/global/exception/ErrorCode.java
  backend/src/main/java/com/ourhour/global/util/PaginationUtil.java
  backend/src/main/resources/db/migration/V11__add_comment_github_sync.sql
Labels: feat

#197 feat(be): swagger 초기설정 및 적용
  backend/build.gradle
  backend/src/main/java/com/ourhour/domain/auth/controller/AuthController.java
  backend/src/main/java/com/ourhour/domain/auth/controller/EmailVerificationController.java
  backend/src/main/java/com/ourhour/domain/auth/controller/PasswordResetController.java
  backend/src/main/java/com/ourhour/domain/board/controller/BoardController.java
  backend/src/main/java/com/ourhour/domain/board/controller/PostController.java
  backend/src/main/java/com/ourhour/domain/chat/controller/ChatRestController.java
  backend/src/main/java/com/ourhour/domain/comment/controller/CommentController.java
  backend/src/main/java/com/ourhour/domain/member/controller/MemberController.java
  backend/src/main/java/com/ourhour/domain/org/controller/OrgController.java
  backend/src/main/java/com/ourhour/domain/org/controller/OrgInvController.java
  backend/src/main/java/com/ourhour/domain/org/controller/OrgMemberController.java
  backend/src/main/java/com/ourhour/domain/project/controller/GitHubController.java
  backend/src/main/java/com/ourhour/domain/project/controller/ProjectController.java
  backend/src/main/java/com/ourhour/domain/project/service/ProjectParticipantService.java
  backend/src/main/java/com/ourhour/domain/user/controller/UserController.java
  backend/src/main/java/com/ourhour/global/config/OpenApiConfig.java
  backend/src/main/java/com/ourhour/global/config/WebSecurityConfig.java
Labels: feat

#200 feat(fe/be): 구성원 초대 관련 백엔드 및 프론트엔드 구현
  backend/src/main/java/com/ourhour/domain/auth/exception/AuthException.java
  backend/src/main/java/com/ourhour/domain/member/repository/MemberRepository.java
  backend/src/main/java/com/ourhour/domain/org/controller/OrgInvController.java
  backend/src/main/java/com/ourhour/domain/org/dto/InviteInfoDTO.java
  backend/src/main/java/com/ourhour/domain/org/dto/OrgInvReqDTO.java
  backend/src/main/java/com/ourhour/domain/org/dto/OrgInvResDTO.java
  backend/src/main/java/com/ourhour/domain/org/exception/OrgInvExcception.java
  backend/src/main/java/com/ourhour/domain/org/mapper/OrgInvMapper.java
  backend/src/main/java/com/ourhour/domain/org/repository/OrgInvBatchRepository.java
  backend/src/main/java/com/ourhour/domain/org/repository/OrgInvRepository.java
  backend/src/main/java/com/ourhour/domain/org/repository/OrgParticipantMemberRepository.java
  backend/src/main/java/com/ourhour/domain/org/service/OrgInvService.java
  backend/src/main/java/com/ourhour/domain/user/repository/UserRepository.java
  backend/src/main/java/com/ourhour/global/exception/ErrorCode.java
  frontend/.tanstack/tmp/router-generator-FOAGMc/628901de2ca439c1e0ea543380d7e0cf
  frontend/src/api/axiosConfig.ts
  frontend/src/api/org/getInvList.ts
  frontend/src/api/org/getInvVerification.ts
  frontend/src/api/org/postAcceptInv.ts
  frontend/src/api/org/postInv.ts
  frontend/src/api/user/postVerifyPwd.ts
  frontend/src/components/org/InvVerification.tsx
  frontend/src/components/org/InvVerificationFail.tsx
  frontend/src/components/org/MemberInvModal.tsx
  frontend/src/components/project/info/ProjectMembersTable.tsx
  frontend/src/constants/badges.ts
  frontend/src/hooks/invite/useAutoAcceptInvitations.ts
  frontend/src/routes/login/index.tsx
  frontend/src/routes/org/$orgId/info/index.tsx
  frontend/src/routes/org/$orgId/invite/fail/index.tsx
  frontend/src/routes/org/$orgId/invite/index.tsx
  frontend/src/routes/org/$orgId/invite/verify/index.tsx
  frontend/src/types/apiTypes.ts
  frontend/src/types/invTypes.ts
  frontend/src/utils/auth/inviteTokenStorage.ts
Labels: feat

#202 refactor(fe): 일부 컴포넌트 리팩토링
  frontend/src/api/auth/signApi.ts
  frontend/src/components/common/MembersTable.tsx
  frontend/src/components/org/MemberInvModal.tsx
  frontend/src/components/project/info/ProjectInfoPage.tsx
  frontend/src/components/project/project-list/ProjectDataTable.tsx
  frontend/src/routes/org/$orgId/info/index.tsx
  frontend/src/stores/projectSlice.ts
Labels: feat

#204 feat(fe): 깃허브 동기화 새로고침 버튼 추가
  frontend/src/components/project/dashboard/ProjectDashboardHeader.tsx
Labels: feat

#212 feat(fe/be): 이슈 태그 CRUD 기능 구현
  backend/src/main/java/com/ourhour/domain/project/controller/ProjectController.java
  backend/src/main/java/com/ourhour/domain/project/dto/IssueReqDTO.java
  backend/src/main/java/com/ourhour/domain/project/dto/IssueSummaryDTO.java
  backend/src/main/java/com/ourhour/domain/project/dto/IssueTagDTO.java
  backend/src/main/java/com/ourhour/domain/project/entity/IssueTagEntity.java
  backend/src/main/java/com/ourhour/domain/project/exception/IssueException.java
  backend/src/main/java/com/ourhour/domain/project/mapper/IssueMapper.java
  backend/src/main/java/com/ourhour/domain/project/mapper/IssueTagMapper.java
  backend/src/main/java/com/ourhour/domain/project/repository/IssueTagRepository.java
  backend/src/main/java/com/ourhour/domain/project/service/IssueService.java
  backend/src/main/java/com/ourhour/global/exception/ErrorCode.java
  backend/src/main/resources/db/migration/V12__add_join_column_issue_tag.sql
  frontend/src/api/project/issueApi.ts
  frontend/src/components/project/dashboard/IssueCard.tsx
  frontend/src/components/project/issue-detail/IssueDetailSidebar.tsx
  frontend/src/components/project/issue-form/AssigneeSelect.tsx
  frontend/src/components/project/issue-form/IssueFormActions.tsx
  frontend/src/components/project/issue-form/IssueFormPage.tsx
  frontend/src/components/project/issue-form/MilestoneSelect.tsx
  frontend/src/components/project/issue-form/StatusSelect.tsx
  frontend/src/components/project/issue-form/TagManagerModal.tsx
  frontend/src/components/project/issue-form/TagSelect.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/hooks/queries/project/useIssueMutations.ts
  frontend/src/hooks/queries/project/useIssueQueries.ts
  frontend/src/styles/colors.ts
Labels: feat

#254 feat(be): 댓글 도메인 단위 테스트 코드 추가
  backend/src/main/java/com/ourhour/domain/comment/controller/CommentController.java
  backend/src/main/java/com/ourhour/domain/comment/dto/CommentCreateReqDTO.java
  backend/src/main/java/com/ourhour/domain/comment/dto/CommentPageResDTO.java
  backend/src/main/java/com/ourhour/domain/comment/dto/CommentUpdateReqDTO.java
  backend/src/main/java/com/ourhour/domain/comment/entity/CommentEntity.java
  backend/src/main/java/com/ourhour/domain/comment/service/CommentService.java
  backend/src/main/java/com/ourhour/domain/project/entity/GitHubSyncableEntity.java
  backend/src/main/java/com/ourhour/domain/project/entity/IssueTagEntity.java
  backend/src/test/java/com/ourhour/domain/comment/controller/CommentControllerTest.java
  backend/src/test/java/com/ourhour/domain/comment/repository/CommentLikeRepositoryTest.java
  backend/src/test/java/com/ourhour/domain/comment/repository/CommentRepositoryTest.java
  backend/src/test/java/com/ourhour/domain/comment/service/CommentLikeServiceTest.java
  backend/src/test/java/com/ourhour/domain/comment/service/CommentServiceTest.java
Labels: refactor

#255 refactor(fe): 자잘한 기능들 추가 및 오류 해결
  frontend/src/api/comment/commentApi.ts
  frontend/src/components/board/CommentSection.tsx
  frontend/src/components/common/MembersTable.tsx
  frontend/src/components/common/detail/DetailContent.tsx
  frontend/src/components/common/detail/DetailHeader.tsx
  frontend/src/components/common/detail/index.ts
  frontend/src/components/common/info-menu/ProfileSheet.tsx
  frontend/src/components/common/left-sidebar/SettingSidebarComponent.tsx
  frontend/src/components/common/left-sidebar/TeamSwitcher.tsx
  frontend/src/components/landing/Header.tsx
  frontend/src/components/member/MemberInfoForm.tsx
  frontend/src/components/org/OrgBasicInfo.tsx
  frontend/src/components/project/dashboard/MilestoneColumn.tsx
  frontend/src/components/project/dashboard/ProjectDashboardHeader.tsx
  frontend/src/components/project/issue-detail/CommentItem.tsx
  frontend/src/components/project/issue-detail/CommentSection.tsx
  frontend/src/components/project/issue-detail/IssueDetailPage.tsx
  frontend/src/components/project/issue-detail/index.ts
  frontend/src/components/project/issue-form/IssueFormPage.tsx
  frontend/src/hooks/queries/comment/useCommentMutations.ts
  frontend/src/hooks/queries/project/useIssueMutations.ts
  frontend/src/pages/board/PostDetailPage.tsx
  frontend/src/routes/login/index.tsx
  frontend/src/routes/org/$orgId/info/index.tsx
  frontend/src/routes/org/$orgId/invite/index.tsx
  frontend/src/routes/org/$orgId/map/index.tsx
  frontend/src/routes/org/$orgId/project/$projectId/index.tsx
  frontend/src/routes/org/$orgId/project/$projectId/issue/create.tsx
  frontend/src/routes/org/route.tsx
  frontend/src/routes/signup/index.tsx
  frontend/src/routes/start.tsx
  frontend/src/stores/orgSlice.ts
  frontend/src/stores/projectSlice.ts
  frontend/src/utils/auth/dateUtils.ts
  frontend/src/utils/auth/routeGuards.ts
  frontend/src/utils/phoneUtils.ts
Labels: refactor

#274 feat(fe/be): 이미지 제거 기능 구현
  .gitignore
  backend/src/main/java/com/ourhour/global/common/controller/StorageController.java
  backend/src/main/java/com/ourhour/global/common/service/ImageCacheEvictionService.java
  backend/src/main/java/com/ourhour/global/common/service/ImageCacheService.java
  backend/src/main/java/com/ourhour/global/common/service/ImageService.java
  frontend/src/api/storage/uploadApi.ts
  frontend/src/components/org/LogoUpload.tsx
  frontend/src/hooks/queries/chat/useChat.ts
  frontend/src/routes/info/$orgId/index.tsx
Labels: feat

#279 feat(fe/be): 자잘한 기능 추가 및 오류 수정
  backend/src/main/java/com/ourhour/domain/project/controller/ProjectController.java
  backend/src/main/java/com/ourhour/domain/project/repository/ProjectParticipantRepository.java
  backend/src/main/java/com/ourhour/domain/project/repository/ProjectRepository.java
  backend/src/main/java/com/ourhour/domain/project/service/ProjectService.java
  frontend/src/api/project/projectApi.ts
  frontend/src/components/project/project-list/ProjectDataTable.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/hooks/queries/project/useProjectQueries.ts
  frontend/src/routes/org/$orgId/project/index.tsx
  frontend/src/stores/authSlice.ts
Labels: feat

#283 feat(fe): 일부 페이지 및 컴포넌트 스켈레톤 ui 적용
  frontend/src/components/board/AllPostsCard.tsx
  frontend/src/components/board/BoardCard.tsx
  frontend/src/components/board/CommentSection.tsx
  frontend/src/components/project/info/ProjectInfoPage.tsx
  frontend/src/components/project/issue-detail/IssueDetailPage.tsx
  frontend/src/components/project/project-list/ProjectDataTable.tsx
  frontend/src/pages/board/BoardListPage.tsx
  frontend/src/pages/board/PostDetailPage.tsx
  frontend/src/routes/org/$orgId/board/index.tsx
  frontend/src/routes/org/$orgId/info/index.tsx
  frontend/src/routes/org/$orgId/map/index.tsx
  frontend/src/routes/org/$orgId/project/$projectId/index.tsx
Labels: feat

#295 feat(fe): 채팅 관련 리팩토링
  frontend/src/components/chat/newChat/ChatRoomNameInput.tsx
  frontend/src/components/chat/newChat/NewChatRoomModal.tsx
  frontend/src/components/chat/room/ChatMessageList.tsx
  frontend/src/components/chat/room/ChatRoomSidebarContent.tsx
  frontend/src/pages/chat/ChatRoomPage.tsx
Labels: feat

#301 feat(fe/be): 실시간 알림 기능 구현
  backend/src/main/java/com/ourhour/domain/auth/controller/AuthController.java
  backend/src/main/java/com/ourhour/domain/chat/controller/ChatController.java
  backend/src/main/java/com/ourhour/domain/chat/dto/ChatRoomEnterReqDTO.java
  backend/src/main/java/com/ourhour/domain/chat/dto/ChatRoomLeaveReqDTO.java
  backend/src/main/java/com/ourhour/domain/chat/service/ChatService.java
  backend/src/main/java/com/ourhour/domain/chat/service/UserLocationService.java
  backend/src/main/java/com/ourhour/domain/comment/controller/CommentController.java
  backend/src/main/java/com/ourhour/domain/comment/service/CommentService.java
  backend/src/main/java/com/ourhour/domain/notification/controller/NotificationController.java
  backend/src/main/java/com/ourhour/domain/notification/dto/NotificationCreateReqDTO.java
  backend/src/main/java/com/ourhour/domain/notification/dto/NotificationDTO.java
  backend/src/main/java/com/ourhour/domain/notification/dto/NotificationPageResDTO.java
  backend/src/main/java/com/ourhour/domain/notification/dto/SSEEventDTO.java
  backend/src/main/java/com/ourhour/domain/notification/entity/NotificationEntity.java
  backend/src/main/java/com/ourhour/domain/notification/enums/NotificationType.java
  backend/src/main/java/com/ourhour/domain/notification/exception/NotificationException.java
  backend/src/main/java/com/ourhour/domain/notification/mapper/NotificationMapper.java
  backend/src/main/java/com/ourhour/domain/notification/repository/NotificationRepository.java
  backend/src/main/java/com/ourhour/domain/notification/service/NotificationEventService.java
  backend/src/main/java/com/ourhour/domain/notification/service/NotificationService.java
  backend/src/main/java/com/ourhour/domain/notification/service/SSENotificationService.java
  backend/src/main/java/com/ourhour/domain/project/service/IssueService.java
  backend/src/main/java/com/ourhour/domain/user/exception/UserException.java
  backend/src/main/java/com/ourhour/global/config/WebSecurityConfig.java
  backend/src/main/java/com/ourhour/global/constant/AuthPath.java
  backend/src/main/java/com/ourhour/global/exception/ErrorCode.java
  backend/src/main/java/com/ourhour/global/jwt/JwtTokenProvider.java
  backend/src/main/java/com/ourhour/global/jwt/filter/JwtAuthenticationFilter.java
  backend/src/main/resources/db/migration/V14__create_notification_table.sql
  backend/src/test/java/com/ourhour/domain/comment/service/CommentServiceTest.java
  docker-compose.dev.yml
  frontend/eslint.config.js
  frontend/src/api/auth/signApi.ts
  frontend/src/api/notification/notificationApi.ts
  frontend/src/components/common/info-menu/NotificationSheet.tsx
  frontend/src/components/common/navigation-menu/NavigationMenuComponent.tsx
  frontend/src/components/project/issue-detail/CommentSection.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/hooks/queries/chat/useChat.ts
  frontend/src/hooks/queries/notification/useInfiniteNotifications.ts
  frontend/src/hooks/queries/notification/useSSE.ts
  frontend/src/stores/notificationSlice.ts
  frontend/src/stores/store.ts
  frontend/src/types/notificationTypes.ts
  frontend/src/utils/auth/tokenUtils.ts
Labels: feat

#302 refactor(fe): 일부 기능 추가 및 오류 수정
  frontend/src/components/board/AllPostsCard.tsx
  frontend/src/components/board/BoardCard.tsx
  frontend/src/components/common/MembersTable.tsx
  frontend/src/components/common/detail/DetailContent.tsx
  frontend/src/components/common/left-sidebar/NavMain.tsx
  frontend/src/components/common/left-sidebar/SettingSidebarComponent.tsx
  frontend/src/components/common/navigation-menu/NavigationMenuComponent.tsx
  frontend/src/components/landing/Header.tsx
  frontend/src/components/project/dashboard/ProjectDashboardHeader.tsx
  frontend/src/hooks/queries/project/useIssueMutations.ts
  frontend/src/pages/board/BoardListPage.tsx
  frontend/src/routes/info/$orgId/index.tsx
  frontend/src/routes/org/$orgId/info/index.tsx
Labels: feat, refactor

#303 feat(be): 프로젝트 데이터 관련 컨텍스트 생성 로직 구현
  llm/app/models/ourhour_models.py
  llm/app/services/context_service.py
  llm/app/services/ourhour_api.py
Labels: feat, refactor

#304 refactor(fe/be): 알림 projectName 추가 및 시멘틱 마크업 적용
  backend/src/main/java/com/ourhour/domain/comment/service/CommentService.java
  backend/src/main/java/com/ourhour/domain/notification/dto/NotificationCreateReqDTO.java
  backend/src/main/java/com/ourhour/domain/notification/dto/NotificationDTO.java
  backend/src/main/java/com/ourhour/domain/notification/entity/NotificationEntity.java
  backend/src/main/java/com/ourhour/domain/notification/mapper/NotificationMapper.java
  backend/src/main/java/com/ourhour/domain/notification/service/NotificationEventService.java
  backend/src/main/java/com/ourhour/domain/project/service/IssueService.java
  backend/src/main/resources/db/migration/V15__add_related_project_name_to_notification.sql
  backend/src/test/java/com/ourhour/domain/comment/service/CommentServiceTest.java
  frontend/index.html
  frontend/src/components/common/ButtonComponent.tsx
  frontend/src/components/common/ModalComponent.tsx
  frontend/src/components/common/info-menu/NotificationSheet.tsx
  frontend/src/components/landing/FeatureCard.tsx
  frontend/src/components/landing/FeaturesSection.tsx
  frontend/src/components/landing/Footer.tsx
  frontend/src/components/landing/Header.tsx
  frontend/src/components/landing/HeroSection.tsx
  frontend/src/components/landing/MonitorMockup.tsx
  frontend/src/main.tsx
  frontend/src/pages/board/BoardListPage.tsx
  frontend/src/pages/board/PostListPage.tsx
  frontend/src/pages/chat/ChatRoomPage.tsx
  frontend/src/types/notificationTypes.ts
Labels: feat, refactor

#310 refactor(fe/be): sse 로직 리팩토링/토큰 초기화 로직 수정
  backend/src/main/java/com/ourhour/domain/notification/controller/NotificationController.java
  backend/src/main/java/com/ourhour/domain/notification/service/SSENotificationService.java
  backend/src/main/java/com/ourhour/global/config/WebSecurityConfig.java
  backend/src/main/java/com/ourhour/global/jwt/filter/JwtAuthenticationFilter.java
  backend/src/main/resources/application.yml
  frontend/src/components/common/info-menu/ProfileSheet.tsx
  frontend/src/components/org/OrgModal.tsx
  frontend/src/hooks/queries/auth/useAuthMutations.ts
  frontend/src/hooks/queries/notification/useInfiniteNotifications.ts
  frontend/src/hooks/queries/notification/useSSE.ts
  frontend/src/hooks/queries/user/useUserMutations.ts
  frontend/src/main.tsx
  frontend/src/utils/auth/tokenUtils.ts
Labels: bug, feat, refactor
