Repository C1Z4/ourHour, pull requests merged in 2025-07, with the labels that each got.

#20 chore: package, import 경로 수정
  backend/src/main/java/com/ourhour/global/common/dto/ApiResponse.java
  backend/src/main/java/com/ourhour/global/common/dto/PageResponse.java
  backend/src/main/java/com/ourhour/global/config/WebConfig.java
  backend/src/main/java/com/ourhour/global/exception/BusinessException.java
  backend/src/main/java/com/ourhour/global/exception/GlobalExceptionHandler.java
Labels: config, feat

#21 chore: 모든 엔티티 import 경로 추가
  .github/workflows/backend-ci.yml
  backend/src/main/java/com/ourhour/domain/board/entity/BoardEntity.java
  backend/src/main/java/com/ourhour/domain/board/entity/PostEntity.java
  backend/src/main/java/com/ourhour/domain/comment/entity/CommentEntity.java
  backend/src/main/java/com/ourhour/domain/comment/entity/CommentLikeEntity.java
  backend/src/main/java/com/ourhour/domain/org/entity/OrgParticipantMemberEntity.java
  backend/src/main/java/com/ourhour/domain/project/entity/IssueEntity.java
  backend/src/main/java/com/ourhour/domain/project/entity/IssueTagEntity.java
  backend/src/main/java/com/ourhour/domain/project/entity/ProjectEntity.java
  backend/src/main/java/com/ourhour/domain/project/entity/ProjectParticipantDepartmentEntity.java
  backend/src/main/java/com/ourhour/domain/project/entity/ProjectParticipantEntity.java
Labels: feat

#28 feat: 게시판 관련 entity 수정 및 추가
  backend/src/main/java/com/ourhour/domain/board/entity/BoardEntity.java
  backend/src/main/java/com/ourhour/domain/board/entity/BoardFixEntity.java
  backend/src/main/java/com/ourhour/domain/board/entity/BoardFixId.java
  backend/src/main/java/com/ourhour/domain/board/entity/PostEntity.java
Labels: feat

#32 feat(be): 회사 목록 조회 (OUR-USER-18)
  backend/src/main/java/com/ourhour/domain/member/controller/.gitkeep
  backend/src/main/java/com/ourhour/domain/member/controller/MemberController.java
  backend/src/main/java/com/ourhour/domain/member/dto/MemberOrgSummaryResDTO.java
  backend/src/main/java/com/ourhour/domain/member/mapper/MemberOrgMapper.java
  backend/src/main/java/com/ourhour/domain/member/repository/.gitkeep
  backend/src/main/java/com/ourhour/domain/member/repository/MemberRepository.java
  backend/src/main/java/com/ourhour/domain/member/sevice/.gitkeep
  backend/src/main/java/com/ourhour/domain/member/sevice/MemberService.java
  backend/src/main/java/com/ourhour/domain/user/enums/Platform.java
Labels: feat

#37 feat(be): 프로젝트 요약 목록 조회 api 구현
  backend/src/main/java/com/ourhour/domain/project/controller/.gitkeep
  backend/src/main/java/com/ourhour/domain/project/controller/ProjectController.java
  backend/src/main/java/com/ourhour/domain/project/dto/.gitkeep
  backend/src/main/java/com/ourhour/domain/project/dto/ProjectSummaryParticipantDTO.java
  backend/src/main/java/com/ourhour/domain/project/dto/ProjectSummaryResDTO.java
  backend/src/main/java/com/ourhour/domain/project/entity/ProjectEntity.java
  backend/src/main/java/com/ourhour/domain/project/mapper/ProjectMapper.java
  backend/src/main/java/com/ourhour/domain/project/repository/.gitkeep
  backend/src/main/java/com/ourhour/domain/project/repository/ProjectParticipantRepository.java
  backend/src/main/java/com/ourhour/domain/project/repository/ProjectRepository.java
  backend/src/main/java/com/ourhour/domain/project/sevice/.gitkeep
  backend/src/main/java/com/ourhour/domain/project/sevice/ProjectService.java
  backend/src/main/java/com/ourhour/global/exception/GlobalExceptionHandler.java
Labels: feat

#41 feat(be): 본인이 소속되어 있는 회사 상세조회 API 구현(OUR-USER-019)
  backend/config/checkstyle/checkstyle.xml
  backend/src/main/java/com/ourhour/domain/member/controller/MemberController.java
  backend/src/main/java/com/ourhour/domain/member/dto/MemberOrgDetailResDTO.java
  backend/src/main/java/com/ourhour/domain/member/exceptions/MemberOrgException.java
  backend/src/main/java/com/ourhour/domain/member/mapper/MemberOrgMapper.java
  backend/src/main/java/com/ourhour/domain/member/repository/MemberRepository.java
  backend/src/main/java/com/ourhour/domain/member/sevice/MemberService.java
Labels: feat

#42 feat: 실시간 채팅 기능 구현을 백엔드 설정 및 테스트 페이지 추가
  backend/src/main/java/com/ourhour/domain/chat/controller/.gitkeep
  backend/src/main/java/com/ourhour/domain/chat/controller/ChatController.java
  backend/src/main/java/com/ourhour/domain/chat/dto/.gitkeep
  backend/src/main/java/com/ourhour/domain/chat/dto/ChatMessageDTO.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/chat/.gitkeep
  frontend/src/components/chat/ChatRoom.tsx
  frontend/src/hooks/queries/chat/.gitkeep
  frontend/src/hooks/queries/chat/useChat.ts
  frontend/src/types/.gitkeep
  frontend/src/types/chatTypes.ts
Labels: feat

#44 fix: DB 수정본 업데이트 및 에러나는 엔티티 수정
  backend/src/main/java/com/ourhour/domain/comment/entity/CommentLikeEntity.java
  backend/src/main/java/com/ourhour/domain/comment/entity/CommentLikeId.java
  backend/src/main/resources/db/migration/V1__init.sql
Labels: bug

#46 feat(be): 프로젝트 참가자 엔티티 수정 반영
  backend/src/main/java/com/ourhour/domain/member/entity/MemberEntity.java
  backend/src/main/java/com/ourhour/domain/project/controller/ProjectController.java
  backend/src/main/java/com/ourhour/domain/project/entity/ProjectParticipantEntity.java
  backend/src/main/java/com/ourhour/domain/project/entity/ProjectParticipantId.java
  backend/src/main/java/com/ourhour/domain/project/mapper/ProjectParticipantMapper.java
Labels: feat

#51 feat(be): 채팅 관련 전체 API 설계 수정 및 구현
  backend/src/main/java/com/ourhour/domain/chat/controller/ChatRestController.java
  backend/src/main/java/com/ourhour/domain/chat/dto/ChatMessageResDTO.java
  backend/src/main/java/com/ourhour/domain/chat/dto/ChatParticipantResDTO.java
  backend/src/main/java/com/ourhour/domain/chat/dto/ChatRoomCreateReqDTO.java
  backend/src/main/java/com/ourhour/domain/chat/dto/ChatRoomListResDTO.java
  backend/src/main/java/com/ourhour/domain/chat/dto/ChatRoomUpdateReqDTO.java
  backend/src/main/java/com/ourhour/domain/chat/dto/ParticipantAddReqDTO.java
  backend/src/main/java/com/ourhour/domain/chat/entity/ChatMessageEntity.java
  backend/src/main/java/com/ourhour/domain/chat/entity/ChatParticipantEntity.java
  backend/src/main/java/com/ourhour/domain/chat/entity/ChatParticipantId.java
  backend/src/main/java/com/ourhour/domain/chat/entity/ChatRoomEntity.java
  backend/src/main/java/com/ourhour/domain/chat/repository/ChatMessageRepository.java
  backend/src/main/java/com/ourhour/domain/chat/repository/ChatParticipantRepository.java
  backend/src/main/java/com/ourhour/domain/chat/repository/ChatRoomRepository.java
  backend/src/main/java/com/ourhour/domain/chat/service/.gitkeep
  backend/src/main/java/com/ourhour/domain/chat/service/ChatService.java
Labels: feat

#57 feat(be): 이슈 CRUD api 구현
  backend/src/main/java/com/ourhour/domain/project/controller/ProjectController.java
  backend/src/main/java/com/ourhour/domain/project/dto/IssueDetailDTO.java
  backend/src/main/java/com/ourhour/domain/project/dto/IssueReqDTO.java
  backend/src/main/java/com/ourhour/domain/project/entity/IssueEntity.java
  backend/src/main/java/com/ourhour/domain/project/mapper/IssueMapper.java
  backend/src/main/java/com/ourhour/domain/project/mapper/MilestoneMapper.java
  backend/src/main/java/com/ourhour/domain/project/repository/IssueRepository.java
  backend/src/main/java/com/ourhour/domain/project/service/IssueService.java
  backend/src/main/java/com/ourhour/domain/project/service/ProjectService.java
  backend/src/main/resources/db/migration/V4__update_issue_table.sql
Labels: feat

#64 feat(be): 회사 도메인 CRUD 구현
  backend/src/main/java/com/ourhour/domain/member/dto/MemberInfoResDTO.java
  backend/src/main/java/com/ourhour/domain/org/controller/OrgController.java
  backend/src/main/java/com/ourhour/domain/org/entity/OrgEntity.java
  backend/src/main/java/com/ourhour/domain/org/mapper/OrgMapper.java
  backend/src/main/java/com/ourhour/domain/org/repository/OrgParticipantMemberRepository.java
  backend/src/main/java/com/ourhour/domain/org/service/OrgService.java
  backend/src/main/java/com/ourhour/domain/project/dto/ProjectNameResDTO.java
  backend/src/main/java/com/ourhour/domain/project/repository/ProjectParticipantRepository.java
Labels: feat

#67 feat(be): 댓글 CRUD api 구현
  backend/src/main/java/com/ourhour/domain/board/repository/.gitkeep
  backend/src/main/java/com/ourhour/domain/board/repository/PostRepository.java
  backend/src/main/java/com/ourhour/domain/comment/controller/.gitkeep
  backend/src/main/java/com/ourhour/domain/comment/controller/CommentController.java
  backend/src/main/java/com/ourhour/domain/comment/dto/.gitkeep
  backend/src/main/java/com/ourhour/domain/comment/dto/CommentCreateReqDTO.java
  backend/src/main/java/com/ourhour/domain/comment/dto/CommentDTO.java
  backend/src/main/java/com/ourhour/domain/comment/dto/CommentPageResDTO.java
  backend/src/main/java/com/ourhour/domain/comment/dto/CommentReqDTO.java
  backend/src/main/java/com/ourhour/domain/comment/dto/CommentResDTO.java
  backend/src/main/java/com/ourhour/domain/comment/dto/CommentUpdateReqDTO.java
  backend/src/main/java/com/ourhour/domain/comment/entity/CommentEntity.java
  backend/src/main/java/com/ourhour/domain/comment/mapper/CommentMapper.java
  backend/src/main/java/com/ourhour/domain/comment/repository/.gitkeep
  backend/src/main/java/com/ourhour/domain/comment/repository/CommentRepository.java
  backend/src/main/java/com/ourhour/domain/comment/service/.gitkeep
  backend/src/main/java/com/ourhour/domain/comment/service/CommentService.java
Labels: feat

#73 feat(be) : Jwt 기반 인증 및 인가 로직 구현
  backend/build.gradle
  backend/src/main/java/com/ourhour/domain/auth/controller/AuthController.java
  backend/src/main/java/com/ourhour/domain/auth/dto/SigninResDTO.java
  backend/src/main/java/com/ourhour/domain/auth/exception/AuthException.java
  backend/src/main/java/com/ourhour/domain/auth/repository/RefreshTokenRepository.java
  backend/src/main/java/com/ourhour/domain/auth/service/AuthService.java
  backend/src/main/java/com/ourhour/domain/org/enums/Role.java
  backend/src/main/java/com/ourhour/domain/user/entity/UserEntity.java
  backend/src/main/java/com/ourhour/domain/user/mapper/UserMapper.java
  backend/src/main/java/com/ourhour/domain/user/repository/UserRepository.java
  backend/src/main/java/com/ourhour/global/config/WebConfig.java
  backend/src/main/java/com/ourhour/global/jwt/.gitkeep
  backend/src/main/java/com/ourhour/global/jwt/JwtTokenProvider.java
  backend/src/main/java/com/ourhour/global/jwt/annotation/OrgAuth.java
  backend/src/main/java/com/ourhour/global/jwt/annotation/OrgId.java
  backend/src/main/java/com/ourhour/global/jwt/aspect/JwtOrgAuthorizationAspect.java
  backend/src/main/java/com/ourhour/global/jwt/dto/Claims.java
  backend/src/main/java/com/ourhour/global/jwt/dto/OrgAuthority.java
  backend/src/main/java/com/ourhour/global/jwt/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/ourhour/global/jwt/mapper/JwtClaimMapper.java
  backend/src/main/java/com/ourhour/global/jwt/mapper/OrgAuthorityMapper.java
  backend/src/main/java/com/ourhour/global/jwt/util/AuthorizationUtil.java
  backend/src/main/java/com/ourhour/global/jwt/util/UserContextHolder.java
  backend/src/test/java/com/ourhour/domain/auth/AuthTest.java
  backend/src/test/java/com/ourhour/domain/auth/AuthTestController.java
  backend/src/test/java/com/ourhour/domain/auth/JwtTest.java
  backend/src/test/java/com/ourhour/domain/auth/PwdTest.java
  backend/src/test/resources/application.yml
Labels: feat

#75 test(be): 인가 관련 테스트 케이스 변경 (@RequestParam -> @PathVariable) 및 오타 수정
  backend/src/main/java/com/ourhour/global/jwt/JwtTokenProvider.java
  backend/src/main/java/com/ourhour/global/jwt/filter/JwtAuthenticationFilter.java
  backend/src/test/java/com/ourhour/domain/auth/AuthTest.java
  backend/src/test/java/com/ourhour/domain/auth/AuthTestController.java
  backend/src/test/java/com/ourhour/domain/auth/JwtTest.java
Labels: feat

#76 refactor(be): DB 및 API 수정에 따른 전체 코드 수정
  backend/src/main/java/com/ourhour/domain/chat/controller/ChatRestController.java
  backend/src/main/java/com/ourhour/domain/chat/dto/ChatMessageResDTO.java
  backend/src/main/java/com/ourhour/domain/chat/dto/ChatRoomCreateReqDTO.java
  backend/src/main/java/com/ourhour/domain/chat/entity/ChatMessageEntity.java
  backend/src/main/java/com/ourhour/domain/chat/entity/ChatParticipantEntity.java
  backend/src/main/java/com/ourhour/domain/chat/entity/ChatRoomEntity.java
  backend/src/main/java/com/ourhour/domain/chat/repository/ChatMessageRepository.java
  backend/src/main/java/com/ourhour/domain/chat/repository/ChatParticipantRepository.java
  backend/src/main/java/com/ourhour/domain/chat/repository/ChatRoomRepository.java
  backend/src/main/java/com/ourhour/domain/chat/service/ChatService.java
  backend/src/main/java/com/ourhour/domain/org/repository/OrgParticipantMemberRepository.java
  backend/src/main/resources/db/migration/V5__add_org_id_to_chatroom.sql
Labels: feat

#81 feat(be): Claim 생성 메소드 구현 및 로그인 API 구현, refreshToken Cookie 저장(OUR-USER-004)
  backend/src/main/java/com/ourhour/domain/auth/controller/AuthController.java
  backend/src/main/java/com/ourhour/domain/auth/dto/SigninResDTO.java
  backend/src/main/java/com/ourhour/domain/auth/entity/RefreshTokenEntity.java
  backend/src/main/java/com/ourhour/domain/auth/exception/AuthException.java
  backend/src/main/java/com/ourhour/domain/auth/repository/RefreshTokenRepository.java
  backend/src/main/java/com/ourhour/domain/auth/service/AuthService.java
  backend/src/main/java/com/ourhour/global/jwt/JwtTokenProvider.java
  backend/src/main/java/com/ourhour/global/jwt/mapper/JwtClaimMapper.java
  backend/src/main/java/com/ourhour/global/jwt/mapper/OrgAuthorityMapper.java
  backend/src/test/java/com/ourhour/domain/auth/JwtTest.java
Labels: feat

#85 feat(fe): 프로젝트 대시보드 페이지 ui 구현 및 import eslint 설정 적용
  frontend/.eslintrc.js
  frontend/eslint.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/chat/ChatMessageList.tsx
  frontend/src/components/chat/ChatRoomList.tsx
  frontend/src/components/chat/ChatRoomListHeader.tsx
  frontend/src/components/common/ButtonComponent.tsx
  frontend/src/components/common/ModalComponent.tsx
  frontend/src/components/common/MoreOptionsPopover.tsx
  frontend/src/components/common/ProfileSheet.tsx
  frontend/src/components/common/StatusBadge.tsx
  frontend/src/components/common/left-sidebar/AppSidebarComponent.tsx
  frontend/src/components/common/left-sidebar/NavMain.tsx
  frontend/src/components/common/left-sidebar/SettingSidebarComponent.tsx
  frontend/src/components/common/left-sidebar/TeamSwitcher.tsx
  frontend/src/components/common/navigation-menu/NavigationMenuComponent.tsx
  frontend/src/components/project/dashboard/IssueCard.tsx
  frontend/src/components/project/dashboard/MilestoneColumn.tsx
  frontend/src/components/project/dashboard/ProjectDashboardHeader.tsx
  frontend/src/components/project/dashboard/index.ts
  frontend/src/components/project/dashboard/mockData.ts
  frontend/src/components/project/project-list/ProjectColumns.tsx
  frontend/src/components/project/project-list/ProjectDataTable.tsx
  frontend/src/components/project/project-list/SortableHeader.tsx
  frontend/src/components/project/project-list/StatusBadge.tsx
  frontend/src/components/project/project-list/dummy.ts
  frontend/src/components/project/project-list/index.ts
  frontend/src/components/ui/avatar.tsx
  frontend/src/components/ui/breadcrumb.tsx
  frontend/src/components/ui/button-variants.ts
  frontend/src/components/ui/button.tsx
  frontend/src/components/ui/dialog.tsx
  frontend/src/components/ui/dropdown-menu.tsx
  frontend/src/components/ui/input.tsx
  frontend/src/components/ui/navigation-menu-styles.ts
  frontend/src/components/ui/navigation-menu.tsx
  frontend/src/components/ui/pagination.tsx
  frontend/src/components/ui/popover.tsx
  frontend/src/components/ui/progress.tsx
  frontend/src/components/ui/separator.tsx
  frontend/src/components/ui/sheet.tsx
  frontend/src/components/ui/sidebar.tsx
  frontend/src/components/ui/table.tsx
  frontend/src/components/ui/tooltip.tsx
  frontend/src/constants/badges.ts
  frontend/src/hooks/queries/chat/useChat.ts
  frontend/src/main.tsx
  frontend/src/routes/$orgId/board/index.tsx
  frontend/src/routes/$orgId/chat/$roomId.tsx
  frontend/src/routes/$orgId/chat/index.tsx
  frontend/src/routes/$orgId/project/$projectId/index.tsx
  frontend/src/routes/$orgId/project/index.tsx
  frontend/src/routes/$orgId/route.tsx
  frontend/src/styles/colors.ts
  frontend/src/types/issueTypes.ts
  frontend/src/types/projectTypes.ts
Labels: feat

#100 feat(fe): axios, redux 기본세팅 및 로그인 페이지 구현
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon/android-chrome-192x192.png
  frontend/public/favicon/android-chrome-512x512.png
  frontend/public/favicon/apple-touch-icon.png
  frontend/public/favicon/favicon-16x16.png
  frontend/public/favicon/favicon-32x32.png
  frontend/public/favicon/favicon.ico
  frontend/public/icons/google.svg
  frontend/public/icons/kakao.svg
  frontend/public/images/landing-1.jpg
  frontend/src/api/auth/postSignin.ts
  frontend/src/api/axiosConfig.ts
  frontend/src/components/auth/ErrorMessage.tsx
  frontend/src/components/auth/LoginForm.tsx
  frontend/src/components/auth/LoginLinks.tsx
  frontend/src/components/auth/SocialLoginButtons.tsx
  frontend/src/components/common/LoadingSpinner.tsx
  frontend/src/components/project/dashboard/ProjectDashboardHeader.tsx
  frontend/src/components/project/info/ProjectMembersTable.tsx
  frontend/src/components/project/modal/MemberSelector.tsx
  frontend/src/components/ui/checkbox.tsx
  frontend/src/constants/messages.ts
  frontend/src/hooks/queries/auth/useAuthMutations.ts
  frontend/src/main.tsx
  frontend/src/routes/login/index.tsx
  frontend/src/stores/.gitkeep
  frontend/src/stores/authSlice.ts
  frontend/src/stores/hooks.ts
  frontend/src/stores/store.ts
  frontend/src/types/apiTypes.ts
  frontend/src/utils/.gitkeep
  frontend/src/utils/auth/errorUtils.ts
  frontend/src/utils/auth/loadingUtils.ts
  frontend/src/utils/auth/retryUtils.ts
  frontend/src/utils/auth/tokenUtils.ts
  frontend/src/utils/storage.ts
  frontend/src/utils/toast.ts
  frontend/src/utils/validation/authValidation.ts
Labels: feat

#106 fix: 채팅 메시지 전송 오류 관련 수정
  frontend/src/components/chat/ChatMessageInput.tsx
  frontend/src/components/chat/ChatMessageList.tsx
  frontend/src/components/chat/ChatRoomList.tsx
  frontend/src/hooks/queries/chat/useChat.ts
  frontend/src/pages/chat/ChatRoomListPage.tsx
  frontend/src/routes/$orgId/chat/$roomId/index.tsx
Labels: bug

#107 feat(be): 채팅 관련 백엔드 로직 및 설정 일부 추가
  backend/src/main/java/com/ourhour/domain/chat/repository/ChatParticipantRepository.java
  backend/src/main/java/com/ourhour/global/config/WebSocketConfig.java
Labels: feat

#118 feat(be): 프로젝트 권한 예외처리
  backend/src/main/java/com/ourhour/domain/project/annotation/ProjectParticipantOnly.java
  backend/src/main/java/com/ourhour/domain/project/aspect/ProjectParticipantAspect.java
  backend/src/main/java/com/ourhour/domain/project/controller/ProjectController.java
  backend/src/main/java/com/ourhour/domain/project/repository/ProjectRepository.java
  backend/src/main/java/com/ourhour/domain/project/service/IssueService.java
  backend/src/main/java/com/ourhour/domain/project/service/MilestoneService.java
  backend/src/main/java/com/ourhour/domain/project/service/ProjectParticipantService.java
Labels: feat

#119 feat(fe): 랜딩페이지 및 회원가입 페이지 구현
  frontend/public/favicon/android-chrome-192x192.png
  frontend/public/favicon/android-chrome-512x512.png
  frontend/public/favicon/apple-touch-icon.png
  frontend/public/favicon/favicon-16x16.png
  frontend/public/favicon/favicon-32x32.png
  frontend/public/favicon/favicon.ico
  frontend/public/images/logo.png
  frontend/src/api/auth/postSendEmailVerification.ts
  frontend/src/api/auth/postSignin.ts
  frontend/src/api/auth/postSignup.ts
  frontend/src/assets/images/logo192.png
  frontend/src/assets/images/logo512.png
  frontend/src/components/auth/SignupForm.tsx
  frontend/src/components/landing/FeatureCard.tsx
  frontend/src/components/landing/FeaturesSection.tsx
  frontend/src/components/landing/Footer.tsx
  frontend/src/components/landing/Header.tsx
  frontend/src/components/landing/HeroSection.tsx
  frontend/src/components/landing/MonitorMockup.tsx
  frontend/src/constants/messages.ts
  frontend/src/hooks/queries/auth/useAuthMutations.ts
  frontend/src/routes/index.tsx
  frontend/src/routes/login/index.tsx
  frontend/src/routes/signup/index.tsx
  frontend/src/styles/index.css
  frontend/src/utils/toast.ts
Labels: feat

#120 feat(be): 회사 멤버 조회 API 추가 및 채팅방 컬럼 수정
  backend/src/main/java/com/ourhour/domain/chat/entity/ChatRoomEntity.java
  backend/src/main/java/com/ourhour/domain/org/controller/OrgMemberController.java
  backend/src/main/java/com/ourhour/domain/org/repository/OrgParticipantMemberRepository.java
  backend/src/main/java/com/ourhour/domain/org/repository/OrgRepository.java
  backend/src/main/java/com/ourhour/domain/org/service/OrgMemberService.java
Labels: feat

#123 feat(fe): 채팅방 이름, 태그 색상 수정 기능 구현
  frontend/src/api/chat/chatApi.ts
  frontend/src/components/chat/list/ChatRoomRow.tsx
  frontend/src/components/chat/room/RenamePopover.tsx
  frontend/src/hooks/queries/chat/useUpdateChatRoomQueries.ts
  frontend/src/pages/chat/ChatRoomPage.tsx
  frontend/src/routes/org/$orgId/chat/$roomId/index.tsx
Labels: feat

#127 feat(be): 구성원 초대 관련 API 구현 및 회사 나가기 API 구현
  backend/src/main/java/com/ourhour/OurhourApplication.java
  backend/src/main/java/com/ourhour/domain/auth/service/AbstractVerificationService.java
  backend/src/main/java/com/ourhour/domain/auth/service/EmailVerificationService.java
  backend/src/main/java/com/ourhour/domain/auth/service/PasswordResetService.java
  backend/src/main/java/com/ourhour/domain/member/entity/MemberEntity.java
  backend/src/main/java/com/ourhour/domain/member/repository/MemberRepository.java
  backend/src/main/java/com/ourhour/domain/org/controller/OrgInvController.java
  backend/src/main/java/com/ourhour/domain/org/controller/OrgMemberController.java
  backend/src/main/java/com/ourhour/domain/org/dto/InviteInfoDTO.java
  backend/src/main/java/com/ourhour/domain/org/dto/OrgInvReqDTO.java
  backend/src/main/java/com/ourhour/domain/org/dto/OrgJoinReqDTO.java
  backend/src/main/java/com/ourhour/domain/org/entity/OrgInvBatchEntity.java
  backend/src/main/java/com/ourhour/domain/org/entity/OrgInvEntity.java
  backend/src/main/java/com/ourhour/domain/org/entity/OrgParticipantMemberEntity.java
  backend/src/main/java/com/ourhour/domain/org/enums/InvStatus.java
  backend/src/main/java/com/ourhour/domain/org/exceptions/OrgException.java
  backend/src/main/java/com/ourhour/domain/org/repository/OrgInvBatchRepository.java
  backend/src/main/java/com/ourhour/domain/org/repository/OrgInvRepository.java
  backend/src/main/java/com/ourhour/domain/org/repository/OrgParticipantMemberRepository.java
  backend/src/main/java/com/ourhour/domain/org/repository/OrgRepository.java
  backend/src/main/java/com/ourhour/domain/org/service/OrgInvService.java
  backend/src/main/java/com/ourhour/domain/org/service/OrgMemberService.java
  backend/src/main/java/com/ourhour/domain/org/service/OrgRoleGuardService.java
  backend/src/main/java/com/ourhour/domain/org/service/OrgService.java
  backend/src/main/java/com/ourhour/domain/user/entity/UserEntity.java
  backend/src/main/java/com/ourhour/domain/user/repository/UserRepository.java
  backend/src/main/java/com/ourhour/domain/user/service/AnonymizeUserService.java
  backend/src/main/resources/db/migration/V8__drop_and_recreate_org_invitations_tables.sql
  backend/src/main/resources/db/undo/V8__undo.sql
Labels: feat

#131 feat(fe): 채팅방 상세 정보 보기 기능 구현
  frontend/src/api/chat/chatApi.ts
  frontend/src/components/chat/list/ChatRoomDetailMaodal.tsx
  frontend/src/components/chat/list/ChatRoomRow.tsx
  frontend/src/components/ui/badge.tsx
  frontend/src/hooks/queries/chat/useChatRoomParticipantsQueries.ts
  frontend/src/types/chatTypes.ts
Labels: feat

#133 feat(be): 초대 정보 목록 조회
  backend/src/main/java/com/ourhour/domain/org/controller/OrgInvController.java
  backend/src/main/java/com/ourhour/domain/org/dto/OrgInvResDTO.java
  backend/src/main/java/com/ourhour/domain/org/mapper/OrgInvMapper.java
  backend/src/main/java/com/ourhour/domain/org/repository/OrgInvBatchRepository.java
  backend/src/main/java/com/ourhour/domain/org/repository/OrgInvRepository.java
  backend/src/main/java/com/ourhour/domain/org/service/OrgInvService.java
Labels: feat

#135 feat(fe): 채팅방 삭제 기능 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/chat/list/ChatRoomDeleteAlert.tsx
  frontend/src/components/chat/list/ChatRoomDetailModal.tsx
  frontend/src/components/chat/list/ChatRoomRow.tsx
  frontend/src/components/ui/alert-dialog.tsx
  frontend/src/hooks/queries/chat/useDeleteChatRoomQueries.ts
Labels: feat

#136 feat(fe/be): 참여중인 프로젝트 이름 목록 조회 api 구현 및 연동(좌측 사이드바)
  backend/src/main/java/com/ourhour/domain/org/controller/OrgController.java
  backend/src/main/java/com/ourhour/domain/org/service/OrgService.java
  backend/src/main/java/com/ourhour/domain/project/repository/ProjectParticipantRepository.java
  frontend/.tanstack/tmp/router-generator-2DGoSE/58298e8077c8d28cdb14588c04e72145
  frontend/src/api/org/getMyProjectList.ts
  frontend/src/components/common/left-sidebar/AppSidebarComponent.tsx
  frontend/src/components/common/left-sidebar/NavMain.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/hooks/queries/org/useMyProjectListQuery.ts
  frontend/src/hooks/queries/project/useProjectParticipantListQuery.ts
Labels: feat

#139 feat: 채팅 참여자 초대 관련 API request 타입 수정 및 프론트엔드 기능 구현
  backend/src/main/java/com/ourhour/domain/chat/controller/ChatRestController.java
  backend/src/main/java/com/ourhour/domain/chat/dto/ParticipantAddReqDTO.java
  backend/src/main/java/com/ourhour/domain/chat/service/ChatService.java
  frontend/src/components/chat/newChat/ChatRoomParticipantSelector.tsx
  frontend/src/components/chat/room/ChatParticipantAddModal.tsx
  frontend/src/components/chat/room/ChatRoomSidebarContent.tsx
  frontend/src/hooks/queries/chat/useAddChatParticipantQueries.ts
  frontend/src/pages/chat/ChatRoomPage.tsx
Labels: feat

#141 feat(be): 게시글 REST API 경로 수정 및 구현
  backend/src/main/java/com/ourhour/domain/board/controller/PostController.java
  backend/src/main/java/com/ourhour/domain/board/dto/PostCreateUpdateReqDTO.java
  backend/src/main/java/com/ourhour/domain/board/entity/PostEntity.java
  backend/src/main/java/com/ourhour/domain/board/mapper/PostMapper.java
  backend/src/main/java/com/ourhour/domain/board/repository/PostRepository.java
  backend/src/main/java/com/ourhour/domain/board/service/PostService.java
Labels: feat

#143 feat(fe/be): 개인정보 페이지 ui 구현 및 api 연동
  backend/src/main/java/com/ourhour/domain/member/controller/MemberController.java
  backend/src/main/java/com/ourhour/domain/member/dto/MyMemberInfoReqDTO.java
  backend/src/main/java/com/ourhour/domain/member/dto/MyMemberInfoResDTO.java
  backend/src/main/java/com/ourhour/domain/member/repository/MemberRepository.java
  backend/src/main/java/com/ourhour/domain/member/service/MemberService.java
  backend/src/main/java/com/ourhour/domain/org/controller/OrgMemberController.java
  backend/src/main/java/com/ourhour/domain/org/mapper/OrgParticipantMemberMapper.java
  backend/src/main/java/com/ourhour/domain/org/repository/OrgParticipantMemberRepository.java
  backend/src/main/java/com/ourhour/domain/user/service/UserService.java
  frontend/src/api/auth/deleteSignout.ts
  frontend/src/api/member/.gitkeep
  frontend/src/api/member/deleteQuitOrg.ts
  frontend/src/api/member/getMyMemberInfo.ts
  frontend/src/api/member/patchPasswordChange.ts
  frontend/src/api/member/putUpdateMyMemberInfo.ts
  frontend/src/api/org/getOrgInfo.ts
  frontend/src/api/org/postCreateOrg.ts
  frontend/src/api/user/deleteUser.ts
  frontend/src/components/common/ProfileSheet.tsx
  frontend/src/components/common/info-menu/ProfileSheet.tsx
  frontend/src/components/common/left-sidebar/NavMain.tsx
  frontend/src/components/common/left-sidebar/SettingSidebarComponent.tsx
  frontend/src/components/common/navigation-menu/NavigationMenuComponent.tsx
  frontend/src/components/member/.gitkeep
  frontend/src/components/member/MemberInfoForm.tsx
  frontend/src/components/member/PasswordChangeForm.tsx
  frontend/src/components/member/WithdrawConfirmModal.tsx
  frontend/src/components/org/LogoUpload.tsx
  frontend/src/components/org/OrgBasicInfo.tsx
  frontend/src/components/org/OrgModal.tsx
  frontend/src/components/project/info/ProjectInfoPage.tsx
  frontend/src/components/project/modal/MemberSelector.tsx
  frontend/src/components/project/modal/ProjectModal.tsx
  frontend/src/constants/queryKeys.ts
  frontend/src/hooks/queries/member/useMyMemberInfoQuery.ts
  frontend/src/hooks/queries/member/useMyMemberInfoUpdateMutation.ts
  frontend/src/hooks/queries/member/usePasswordUpdateMutation.ts
  frontend/src/hooks/queries/member/useQuitOrgMutation.ts
  frontend/src/hooks/queries/user/useUserDeleteMutation.ts
  frontend/src/routes/info/$orgId/index.tsx
  frontend/src/routes/info/password.tsx
  frontend/src/routes/info/route.tsx
  frontend/src/routes/info/withdraw.tsx
  frontend/src/routes/org/$orgId/info/index.tsx
  frontend/src/routes/start.tsx
  frontend/src/stores/memberSlice.ts
  frontend/src/stores/store.ts
  frontend/src/utils/auth/tokenUtils.ts
Labels: feat

#149 feat(fe/be): 이메일 인증 관련 프론트 및 백엔드 구현
  backend/src/main/java/com/ourhour/domain/auth/controller/AuthController.java
  backend/src/main/java/com/ourhour/domain/auth/service/AuthService.java
  backend/src/main/java/com/ourhour/domain/auth/service/EmailVerificationService.java
  backend/src/main/java/com/ourhour/global/jwt/filter/JwtAuthenticationFilter.java
  frontend/index.html
  frontend/src/api/auth/getCheckEmail.ts
  frontend/src/api/auth/getEmailVerification.ts
  frontend/src/api/axiosConfig.ts
  frontend/src/components/auth/EmailVerification.tsx
  frontend/src/components/auth/EmailVerificationFail.tsx
  frontend/src/components/auth/SignupForm.tsx
  frontend/src/components/landing/Header.tsx
  frontend/src/main.tsx
  frontend/src/routes/auth/email-verification/index.tsx
  frontend/src/routes/auth/fail/index.tsx
  frontend/src/routes/login/index.tsx
  frontend/src/routes/signup/index.tsx
  frontend/src/utils/auth/pendingSignupStorage.ts
  frontend/src/utils/toast.ts
  package-lock.json
Labels: feat

#162 fix(fe): 채팅 목록 UI 개선 및 나가기 기능 수정
  frontend/src/api/chat/chatApi.ts
  frontend/src/components/chat/list/ChatRoomDetailModal.tsx
  frontend/src/components/chat/list/ChatRoomExitAlert.tsx
  frontend/src/components/chat/list/ChatRoomList.tsx
  frontend/src/components/chat/list/ChatRoomRow.tsx
  frontend/src/components/chat/room/ChatRoomSidebarContent.tsx
  frontend/src/hooks/queries/chat/useDeleteChatParticipantMutation.ts
Labels: feat

#169 feat(fe): 구성원 삭제 시 비밀번호 입력 구현
  frontend/src/routes/org/$orgId/info/index.tsx
Labels: feat
